{
 "title": "EPSON XP-8600 Series",
 "tags": [
  "epson",
  "printer",
  "lab"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "jobs", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "up{job=~\"$jobs\"}"
    }
   },
   { "name": "status", "query": { "query": "hrPrinterStatus" } }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Printer Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prtGeneralPrinterName{job=\"epson_printer_snmp\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer Last Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job=\"epson_printer_snmp\", instance=\"$instance\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrPrinterStatus{job=\"epson_printer_snmp\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Critical Alert Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prtAlertCriticalEvents{job=\"$jobs\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer Serial Number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prtGeneralSerialNumber{job=\"epson_printer_snmp\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Printer Supplies Status",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prtMarkerSuppliesLevel{job=\"$jobs\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}